phases:
- template: phase.yml
  parameters:
    name: macOS
    queueName: Hosted macOS Preview

- template: phase.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'

- template: phase.yml
  parameters:
    name: Windows
    queueName: Hosted VS2017
